#!/usr/bin/env bash
# Link adb and fastboot
wslbin=~/.local/bin/wsl

createlink() {
    local tool=$1
    if which "$tool.exe" &>/dev/null && ! which "$tool" &>/dev/null; then
        ln -sf "$(which $tool.exe)" $wslbin/$1
    fi
}

mkdir -p $wslbin
createlink adb
createlink fastboot
