vim.g.mapleader = " "
vim.o.expandtab = true
vim.o.number = true
vim.o.relativenumber = true
vim.o.scrolloff = 8
vim.o.showmode = false
vim.o.signcolumn = "yes"
vim.o.undofile = true
vim.o.updatetime = 50
vim.o.wrap = false
