# disable border when there's only single window
windowrule {
    name = windowrule-1
    border_size = 0
    match:workspace = w[tv1] f[-1]
    match:float = 0
}
windowrule {
    name = windowrule-2
    workspace = 1
    match:class = (brave.*|chromium|helium|zen)
}
windowrule {
    name = windowrule-3
    workspace = 2
    match:class = jetbrains-.*
}
windowrule {
    name = windowrule-4
    no_focus = on
    match:class = jetbrains-.*
    match:title = win\d+$
}
windowrule {
    name = windowrule-5
    allows_input = on
    match:class = jetbrains-.*
    match:title = negative:win\d+$
}
windowrule {
    name = windowrule-6
    workspace = 3
    match:class = (discord|vesktop|org\.tele.*)
}
windowrule {
    name = windowrule-7
    workspace = 4
    match:class = gimp
}
windowrule {
    name = windowrule-8
    workspace = name:game
    no_anim = on
    match:class = steam_app.*$
    match:title = \w+
}
windowrule {
    name = windowrule-9
    workspace = name:game
    float = on
    border_size = 0
    no_anim = on
    match:class = steam_app.*
    match:title = ^$
}
# floating windows
    windowrule {
    name = windowrule-10
    float = on
    match:class = file-.*
    match:title = Export.*
}
windowrule {
    name = windowrule-11
    float = on
    match:class = xdg-desktop-portal-.*
}
windowrule {
    name = windowrule-12
    float = on
    border_size = 0
    match:title = Emulator
}
windowrule {
    name = windowrule-13
    workspace = w
    float = on
    pin = on
    no_initial_focus = on
    move = ((monitor_w*1)-460) ((monitor_h*1)-320)
    size = 390 220
    match:title = ^.icture.in..icture$
}
windowrule {
    name = windowrule-14
    float = on
    dim_around = on
    size = (monitor_w*0.8) (monitor_h*0.8)
    match:class = .*.Loupe$
}
windowrule {
    name = windowrule-15
    float = on
    dim_around = on
    size = (monitor_w*0.5) (monitor_h*0.6)
    match:class = waypaper
}
windowrule {
    name = windowrule-16
    float = on
    size = (monitor_w*0.2) (monitor_h*0.7)
    move = ((monitor_w*0.75)) ((monitor_h*0.15))
    match:class = localsend
}
